Models/ErrorViewModel.cs
using System;

namespace GL_sensors_v0_4.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Measurement.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GL_sensors_v0_4.Models
{
    public class Measurement
    {
        public int Id { get; set; }             //PK
        public int sensorId { get; set; }       //corresponding sensor id
        public int pm_1_0 { get; set; }         //pm_1_0
        public int pm_2_5 { get; set; }         //pm_2_5    -       PM2.5 is particulate matter 2.5 micrometers or less in diameter.
        public int pm_10 { get; set; }          //pm_10     -       PM10 is particulate matter 10 micrometers or less in diameter
        public double temp { get; set; }        //temperature (°C)
        public double hum { get; set; }         //humidity (%)
        public DateTime time { get; set; }      //time stamp of the measurment of format ("%Y-%m-%d %H:%M:%S")

        public string ToJson()
        {
            string json;
            json = JsonConvert.SerializeObject(this);
            return json;
        }
    
    
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GL_sensors_v0_4.Models;

namespace GL_sensors_v0_4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Images()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MeasurementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GL_sensors_v0_4.Data;
using GL_sensors_v0_4.Models;
using Newtonsoft.Json;
using System.Runtime.CompilerServices;

namespace GL_sensors_v0_4.Controllers
{
    public class MeasurementsController : Controller
    {
        private readonly SnakeyDataContext _context = new SnakeyDataContext();

        //public MeasurementsController(SnakeyDataContext context)
        //{
        //    _context = context;
        //}

        [HttpGet]
        public ActionResult GetLast(int id)
        {
            //write logic here to get data
            var output = _context.Measurements.Where(e => e.sensorId == id-1).ToList();
            //List<Measurement> array = output.ToList();
            Measurement last = new Measurement();
            last = output[0];
            foreach(var i in output)
            {
                if (i.time > last.time) last = i;
            }
            string json = last.ToJson();
            //JsonObject _json = json;
            return Json(json);
            
        }

        public async Task<IActionResult> ReturnMeasurements(int? id)
        {
            //var query = from Measurements in _context
            //            where Measurements.sensorId == id
            //            select Measurements.temp;
            var gL_Sensors_v0_2Context = _context.Measurements.Where(e => e.sensorId == id);
            return View(await gL_Sensors_v0_2Context.ToListAsync());
            //return View();
        }


        // GET: Measurements
        public async Task<IActionResult> Index()
        {
            return View(await _context.Measurements.ToListAsync());
        }

        // GET: Measurements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var measurement = await _context.Measurements
                .FirstOrDefaultAsync(m => m.Id == id);
            if (measurement == null)
            {
                return NotFound();
            }

            return View(measurement);
        }

        // GET: Measurements/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Measurements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,sensorId,pm_1_0,pm_2_5,pm_10,temp,hum,time")] Measurement measurement)
        {
            if (ModelState.IsValid)
            {
                _context.Add(measurement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(measurement);
        }

        // GET: Measurements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var measurement = await _context.Measurements.FindAsync(id);
            if (measurement == null)
            {
                return NotFound();
            }
            return View(measurement);
        }

        // POST: Measurements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,sensorId,pm_1_0,pm_2_5,pm_10,temp,hum,time")] Measurement measurement)
        {
            if (id != measurement.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(measurement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeasurementExists(measurement.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(measurement);
        }

        // GET: Measurements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var measurement = await _context.Measurements
                .FirstOrDefaultAsync(m => m.Id == id);
            if (measurement == null)
            {
                return NotFound();
            }

            return View(measurement);
        }

        // POST: Measurements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var measurement = await _context.Measurements.FindAsync(id);
            _context.Measurements.Remove(measurement);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MeasurementExists(int id)
        {
            return _context.Measurements.Any(e => e.Id == id);
        }
    }
}

Views/Home/Images.cshtml
@{
    ViewData["Title"] = "Images";
}

<head>
    Office Layout:
    <script src="https://d3js.org/d3.v3.min.js"></script>
    <link rel="stylesheet" href="~/css/OfficeLayoutStyle.css" />
</head>

<body>
    <div class="box" , id="tlo">

        <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
        <script type="text/javascript">

            //LIST OF NORMS
            var NORM_TEMP = "25";
            var NORM_HUM = "50";
            var NORM_PM_1_0 = "10";
            var NORM_PM_2_5 = "50";
            var NORM_PM_10 = "100";

            //INITIAL CONDITIONS
            var radius = 0;
            var numberOfTheDevices = 3;
            var device1 = { id: "1", hight: "224", width: "248", pm_2_5norm: NORM_PM_2_5, pm_1_0norm: NORM_PM_1_0, pm_10norm: NORM_PM_10, tempnorm: NORM_TEMP, humnorm: NORM_HUM }
            var measure1 = { id: "1", pm_2_5: "0", pm_1_0: "0", pm_10: "0", temp: "0", hum: "0" }
            var device2 = { id: "2", hight: "353", width: "156", pm_2_5norm: NORM_PM_2_5, pm_1_0norm: NORM_PM_1_0, pm_10norm: NORM_PM_10, tempnorm: NORM_TEMP, humnorm: NORM_HUM }
            var measure2 = { id: "2", pm_2_5: "0", pm_1_0: "0", pm_10: "0", temp: "0", hum: "0" }
            var device3 = { id: "3", hight: "333", width: "208", pm_2_5norm: NORM_PM_2_5, pm_1_0norm: NORM_PM_1_0, pm_10norm: NORM_PM_10, tempnorm: NORM_TEMP, humnorm: NORM_HUM }
            var measure3 = { id: "3", pm_2_5: "0", pm_1_0: "0", pm_10: "0", temp: "0", hum: "0" }
            var newmeasure = { id: "0", pm_2_5: "0", pm_1_0: "0", pm_10: "0", temp: "0", hum: "0" }

            /*
            var pm_2_5tab =[0, 0, 0];
            var pm_1_0tab =[0, 0, 0];
            var pm_10tab =[0, 0, 0];
            var temptab =[0, 0, 0];
            var humtab =[0, 0, 0];
            var ajajaj = ['1', '2', '3'];
            for (var i = 0; i < 3; ++i)
            {
                var j = ajajaj[i];
                $(document).ready(function () {
                    //$("#btnGetDetails").click(function () {
                    $.ajax({
                        //base address/controller/Action
                        url: 'https://localhost:44327/Measurements/GetLast',
                        type: 'GET',
                        data: {
                            //Passing Input parameter
                            id: j
                        },
                        success: function (result) {
                            //write something
                            //alert(result);
                            //alert("success");
                            var newmeasure = JSON.parse(result);
                            console.log(newmeasure);
                            //var pm = newmeasure.pm_10;
                            //console.log(pm);
                            pm_2_5tab[i] = newmeasure.pm_2_5;
                            pm_1_0tab[i] = newmeasure.pm_1_0;
                            pm_10tab[i] = newmeasure.pm_10;
                            temptab[i] = newmeasure.temp;
                            humtab[i] = newmeasure.hum;
                            //console.log(pm_2_5tab[i]);
                        },
                        error: function () {
                            alert("error");
                        }
                    });
                    return false;
                    //});
                });
            }
                measure1.pm_2_5 = parseInt(pm_2_5tab[0]);
                measure2.pm_2_5 = String(pm_2_5tab[1]);
                measure3.pm_2_5 = pm_2_5tab[2];

                measure1.pm_1_0 = pm_1_0tab[0];
                measure2.pm_1_0 = pm_1_0tab[1];
                measure3.pm_1_0 = pm_1_0tab[2];

                measure1.pm_10 = pm_10tab[0];
                measure2.pm_10 = pm_10tab[1];
                measure3.pm_10 = pm_10tab[2];

                measure1.temp = temptab[0];
                measure2.temp = temptab[1];
                measure3.temp = temptab[2];

                measure1.hum = humtab[0];
                measure2.hum = humtab[1];
            measure3.hum = humtab[2];

            console.log(measure1);
            console.log(measure2);
            console.log(measure3);



            function measure_update(measure, newmeasure) {
                measure.pm_2_5 = newmeasure.pm_2_5;//.toString();
                measure.pm_1_0 = newmeasure.pm_1_0.toString();
                measure.pm_10 = newmeasure.pm_10.toString();
                measure.temp = newmeasure.temp.toString();
                measure.hum = newmeasure.hum.toString();

            }

            switch (Id) {
                case 1:
                    //measure_update(measure1, newmeasure);
                    measure1 = newmeasure;
                    console.log("meas1 upd");
                    break;
                case 2:
                    //measure_update(measure2, newmeasure);
                    measure2 = newmeasure;
                    console.log("meas2 upd");
                    break;
                case 3:
                    //measure_update(measure3, newmeasure);
                    measure3 = newmeasure;
                    console.log("meas3 upd");
                    break;
            }


            if (Id == 1) {
                measure1 = newmeasure;
                console.log("meas1 upd");
            }
            else if (Id == 2) {
                measure2 = newmeasure;
                console.log("meas2 upd");
            }
            else if (Id == 3) {
                measure3 = newmeasure;
                console.log("meas3 upd");
            }
            */

            var canvas = d3.select("#tlo")
                .append("svg")
                .attr("width", 1000)
                .attr("height", 1000);

            function trans(circleAct, rad) {
                circleAct.transition()
                    .duration(1000)
                    .attr("r", 20 + (rad * 2))
                    .transition()
                    .duration(1)
                    .attr("r", 0)
                    .each("end", function () { trans(circleAct, rad); });
            }

            function alert(wid, hig, col, rad) {
                var circ = canvas.append("circle")
                    .attr("cx", wid)
                    .attr("cy", hig)
                    .attr("r", 3)
                    .attr("stroke", "black")
                    .attr("fill", col);

                var circle = canvas.append("circle")
                    .attr("cx", wid)
                    .attr("cy", hig)
                    .attr("r", 10)
                    .attr("fill", col)
                    .attr("opacity", 0.5);

                trans(circle, rad);
            }

            function deviceChooser2(device, measure) {
                if (device.tempnorm < measure.temp) {
                    color = "green";
                    var diff = parseInt(measure.temp) - parseInt(device.tempnorm)
                    radius = Math.max(0, diff);
                    alert(device.width, device.hight, color, radius);
                }
                if (device.pm_1_0norm < measure.pm_1_0) {
                    color = "red"
                    radius = (measure.pm_1_0 - device.pm_1_0norm);
                    alert(device.width, device.hight, color, radius);
                }
            }

            function deviceChooser(device, measure) {
                if (device.pm_1_0norm < measure.pm_1_0) {
                    color = "red"
                    var diff = parseInt(measure.pm_1_0) - parseInt(device.pm_1_0norm)
                    radius = Math.max(0, diff);
                    alert(device.width, device.hight, color, radius);
                }
                else if (device.pm_2_5norm < measure.pm_2_5) {
                    color = "orange"
                    var diff = parseInt(measure.pm_2_5) - parseInt(device.pm_2_5norm)
                    radius = Math.max(0, diff);
                    alert(device.width, device.hight, color, radius);
                }
                else if (device.pm_10norm < measure.pm_10) {
                    color = "yellow"
                    var diff = parseInt(measure.pm_10) - parseInt(device.pm_10norm)
                    radius = Math.max(0, diff);
                    alert(device.width, device.hight, color, radius);
                }
                else if (device.tempnorm < measure.temp) {
                    color = "green";
                    var diff = parseInt(measure.temp) - parseInt(device.tempnorm)
                    radius = Math.max(0, diff);
                    alert(device.width, device.hight, color, radius);
                }
                else if (device.humnorm < measure.hum) {
                    color = "yellow"
                    var diff = parseInt(measure.hum) - parseInt(device.humnorm)
                    radius = Math.max(0, diff);
                    alert(device.width, device.hight, color, radius);
                }
                //console.log("device chooser");
            }

            function update(device, measure) {
                $(document).ready(function () {
                    //$("#btnGetDetails").click(function () {
                    $.ajax({
                        //base address/controller/Action
                        url: 'https://localhost:44327/Measurements/GetLast',
                        type: 'GET',
                        data: {
                            //Passing Input parameter
                            id: measure.id
                        },
                        success: function (result) {
                            //write something
                            //alert(result);
                            //alert("success");
                            var last = JSON.parse(result);

                            //var pm = newmeasure.pm_10;
                            //console.log(pm);
                            //console.log(newmeasure.pm_2_5);
                            //console.log(typeof (newmeasure.pm_2_5));
                            //console.log(typeof (measure1.pm_2_5));
                            measure.pm_1_0 = last.pm_1_0;
                            measure.pm_10 = last.pm_10;
                            measure.temp = last.temp;
                            measure.hum = last.hum;
                            measure.pm_2_5 = last.pm_2_5;
                            measure.id = last.sensorId;
                            deviceChooser(device, measure);
                            //deviceChooser2(device, measure);
                        },
                        error: function () {
                            console.log("error");
                        }
                    });
                    return false;
                    //});
                });
            }
            update(device1, measure1);
            update(device2, measure2);
            update(device3, measure3);
            console.log("mea1:");
            console.log(measure1);
            console.log("mea2:");
            console.log(measure2);
            console.log("mea3:");
            console.log(measure3);

            /*
            for (var i = 1; i <= numberOfTheDevices; i++) {
                id = i;
                deviceChooser(id)
            }
            */
            console.log("KONIEC");
        </script>

    </div>

    <svg width="500" height="200">
        <circle cx="20" cy="20" r="20" fill="red" opacity="0.5" />
        <circle cx="70" cy="20" r="20" fill="orange" opacity="0.5" />
        <circle cx="120" cy="20" r="20" fill="yellow" opacity="0.5" />
        <circle cx="170" cy="20" r="20" fill="blue" opacity="0.5" />
        <circle cx="170" cy="20" r="20" fill="green" opacity="0.5" />
        <circle cx="220" cy="20" r="20" fill="blue" opacity="0.5" />
        <text x="20" y="20"
              font-family="sans-serif"
              font-size="10px"
              text-anchor="middle"
              fill="black">PM1.0</text>
        <text x="70" y="20"
              font-family="sans-serif"
              font-size="10px"
              text-anchor="middle"
              fill="black">PM2.5</text>
        <text x="120" y="20"
              font-family="sans-serif"
              font-size="10px"
              text-anchor="middle"
              fill="black">PM10</text>
        <text x="170" y="20"
              font-family="sans-serif"
              font-size="10px"
              text-anchor="middle"
              fill="black">Tmp</text>
        <text x="220" y="20"
              font-family="sans-serif"
              font-size="10px"
              text-anchor="middle"
              fill="black">Hmdt</text>s
    </svg>

    <img src="~/data/images/OfficeLayoutWithIDs.png" alt="Workplace" style="position:absolute; top:0; left:0; margin-left:402px; margin-top:198px; margin-bottom:20px; opacity:0; *filter: Alpha(opacity=0);" usemap="#workmap" />

    <map name="workmap">
        <area shape="rect" coords="140,320,180,380" alt="Computer" href="@Url.Action("ReturnMeasurements", "Measurements")?id=1">
        <area shape="rect" coords="190,320,290,380" alt="Phone" href="@Url.Action("ReturnMeasurements", "Measurements")?id=2">
        <area shape="rect" coords="205,180,269,288;" alt="Phone" href="@Url.Action("ReturnMeasurements", "Measurements")?id=4">
    </map>

</body>

Views/Home/OLDImages.cshtml
@{
    ViewData["Title"] = "Images";
}

<h1>Office Layout:</h1>

<body>
    <img src="~/data/images/OfficeLayoutWithIDs.png" alt="Workplace" usemap="#workmap" />

    <map name="workmap">
        <area shape="rect" coords="140,320,180,380" alt="Computer" href="@Url.Action("ReturnMeasurements", "Measurements")?id=1">
        <area shape="rect" coords="190,320,290,380" alt="Phone" href="@Url.Action("ReturnMeasurements", "Measurements")?id=2">
    </map>
</body>

Views/Home/OLDOLDImages.cshtml
@{
    ViewData["Title"] = "Images";
}


<head>
    Office Layout:

    <script src="https://d3js.org/d3.v3.min.js"></script>

    <link rel="stylesheet" href="~/css/officeMap.css" />

</head>


<body>

    <div class="box" , id="tlo">
        <script>


                var device1 = { id: "1", hight: "340", width: "379", pm_1_0norm: "2", pm_2_5norm: "2", pm_10norm: "2" }
                var measure1 = { pm_1_0: "0", pm_2_5: "0", pm_10: "0" }
                var device2 = { id: "2", hight: "535", width: "240", pm_1_0norm: "2", pm_2_5norm: "2", pm_10norm: "2" }
                var measure2 = { pm_1_0: "0", pm_2_5: "0", pm_10: "0" }
                var device3 = { id: "3", hight: "506", width: "319", pm_1_0norm: "2", pm_2_5norm: "2", pm_10norm: "2" }
                var measure3 = { pm_1_0: "0", pm_2_5: "0", pm_10: "0" }

                var radius = 0;

                var canvas = d3.select("#tlo")
                    .append("svg")
                    .attr("width", 1000)
                    .attr("height", 1000);

                function trans(circleAct, rad) {
                    circleAct.transition()
                        .duration(1000)
                        .attr("r", 20 + (rad * 2))
                        .transition()
                        .duration(1)
                        .attr("r", 0)
                        .each("end", function () { trans(circleAct, rad); });
                }

                function alert(wid, hig, col, rad) {
                    var circ = canvas.append("circle")
                        .attr("cx", wid)
                        .attr("cy", hig)
                        .attr("r", 3)
                        .attr("stroke", "black")
                        .attr("fill", col);

                    var circle = canvas.append("circle")
                        .attr("cx", wid)
                        .attr("cy", hig)
                        .attr("r", 10)
                        .attr("fill", col)
                        .attr("opacity", 0.5);

                    trans(circle, rad);
                }


                function deviceChooser(id) {
                    switch (id) {

                        case 1:
                            if (device1.pm_1_0norm < measure1.pm_1_0) {
                                color = "red"
                                radius = measure1.pm_1_0 - device1.pm_1_0norm;
                                alert(device1.width, device1.hight, color, radius);
                            }
                            else if (device1.pm_2_5norm < measure1.pm_2_5) {
                                color = "orange"
                                radius = measure1.pm_2_5 - device1.pm_2_5norm;
                                alert(device1.width, device1.hight, color, radius);
                            }
                            else if (device1.pm_10norm < measure1.pm_10) {
                                color = "yellow"
                                radius = measure1.pm_10 - device1.pm_10norm;
                                alert(device1.width, device1.hight, color, radius);
                            }
                            break;

                        case 2:
                            if (device2.pm_1_0norm < measure2.pm_1_0) {
                                color = "red"
                                radius = measure2.pm_1_0 - device2.pm_1_0norm;
                                alert(device2.width, device2.hight, color, radius);
                            }
                            else if (device2.pm_2_5norm < measure2.pm_2_5) {
                                color = "orange"
                                radius = measure2.pm_2_5 - device2.pm_2_5norm;
                                alert(device2.width, device2.hight, color, radius);
                            }
                            else if (device2.pm_10norm < measure2.pm_10) {
                                color = "yellow"
                                radius = measure2.pm_10 - device2.pm_10norm;
                                alert(device2.width, device2.hight, color, radius);
                            }
                            break;

                        case 3:
                            if (device3.pm_1_0norm < measure3.pm_1_0) {
                                color = "red"
                                radius = measure3.pm_1_0 - device3.pm_1_0norm;
                                alert(device3.width, device3.hight, color, radius);
                            }
                            else if (device3.pm_2_5norm < measure3.pm_2_5) {
                                color = "orange"
                                radius = measure3.pm_2_5 - device3.pm_2_5norm;
                                alert(device3.width, device3.hight, color, radius);
                            }
                            else if (device3.pm_10norm < measure3.pm_10) {
                                color = "yellow"
                                radius = measure3.pm_10 - device3.pm_10norm;
                                alert(device3.width, device3.hight, color, radius);
                            }
                            break;
                    }
                }





                var numberOfTheDevices = 3

                measure1.pm_1_0 = 5;
                measure1.pm_2_5 = 5;
                measure2.pm_10 = 10;
                measure2.pm_1_0 = 2;
                measure3.pm_2_5 = 15;
                measure3.pm_10 = 5;

                for (var i = 1; i <= numberOfTheDevices; i++) {
                    id = i;
                    deviceChooser(id)
                }



            </script>




    </div>

    <img src="~/data/images/OfficeLayoutWithIDs.png" alt="Workplace" usemap="#workmap" />

    <map name="#workmap">
        <area shape="rect" coords="140,320,180,380" alt="Computer" href="@Url.Action("ReturnMeasurements", "Measurements")?id=1">
        <area shape="rect" coords="190,320,290,380" alt="Phone" href="@Url.Action("ReturnMeasurements", "Measurements")?id=2">
    </map>

</body>

Views/Measurements/GetLast.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h6>TEST</h6>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GL_sensors_v0.4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GL_sensors_v0_4</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Measurements" asp-action="Index">Measurements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Images">Office Layout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GL_sensors_v0_4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>